# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20170816_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='updated',
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
