# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20170816_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
