# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20170816_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
