# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anggaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paket', models.CharField(blank=True, max_length=300, null=True)),
                ('nama_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggaran.Kegiatan')),
            ],
        ),
    ]
