# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anggaran', '0002_paket'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsulanDanaAnggaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggaran.Kegiatan')),
                ('nama_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anggaran.Program')),
            ],
        ),
    ]
