# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggaran', '0003_usulandanaanggaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usulandanaanggaran',
            name='nama_kegiatan',
        ),
    ]
