# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anggaran', '0004_remove_usulandanaanggaran_nama_kegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulandanaanggaran',
            name='nama_kegiatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anggaran.Kegiatan'),
        ),
    ]
