# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anggaran', '0005_usulandanaanggaran_nama_kegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usulandanaanggaran',
            name='jumlah_anggaran',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usulandanaanggaran',
            name='nama_usulan',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usulandanaanggaran',
            name='paket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anggaran.Paket'),
        ),
        migrations.AddField(
            model_name='usulandanaanggaran',
            name='tahun_usulan',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usulandanaanggaran',
            name='nama_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anggaran.Program'),
        ),
    ]
