# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggaran', '0008_auto_20170817_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usulandanaanggaran',
            name='tahun_usulan',
            field=models.IntegerField(choices=[('2016', '2016'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015')], max_length=4),
        ),
    ]
